### ISSUE TITLE
The statistics page is not working.

### ISSUE THREAD

**Issue by PiterMobile** [PiterMobile/macher#8]
Server Error (500)

**Comment by PiterMobile** [comment]
It seems that if the betting table is empty, the sort and display method returns an error.
`2022-11-17 11:16:28,914: Internal Server Error: /stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/rtspl/macher/em/bet/views.py", line 138, in get_context_data
    context['for_poland'] = self.for_team('Polska')
  File "/home/rtspl/macher/em/bet/views.py", line 124, in for_team
    return self.display(q, 2, 'score')
  File "/home/rtspl/macher/em/bet/views.py", line 116, in display
    item = obj[cut][target]
IndexError: list index out of range`
